defaults: &defaults
  docker:
    - image: circleci/python:3.6.1

version: 2
jobs:
   build:
     <<: *defaults
     steps:
       - checkout

       - restore_cache:
           key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

       - run:
           name: Prepare
           command: |
             export PATH="$HOME/.local/bin:$PATH"
             pip install --user pipenv
             pip install --user awscli
             python3 -m venv venv
             . venv/bin/activate
             pipenv install

       - run:
           name: Build Zip
           command: |
             mkdir build
             mkdir dist
             cp methods.py build/
             cp helpers.py build/
             cp decorators.py build/
             cp -R venv/lib/python3.6/site-packages/* build/
             cd build; chmod -R u=rwx,go=r .; zip -r ../dist/secureletter-0.0.11.zip .

       - store_artifacts:
           path: dist/secureletter-0.0.11.zip

       - save_cache:
           key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
           paths:
             - venv
             - /home/circleci/.local

       - persist_to_workspace:
           root: /home/circleci/project
           paths:
             - dist/secureletter-0.0.11.zip
             - cloudformation_stack.yaml
             - Pipfile.lock

   upload:
     <<: *defaults
     steps:
       - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/circleci/project

       - restore_cache:
           key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

       - run:
           name: Deploy Resources to S3
           command: |
             export PATH="$HOME/.local/bin:$PATH"
             aws s3 cp dist/secureletter-0.0.11.zip s3://$S3_BUCKET/
             aws s3 cp cloudformation_stack.yaml s3://$S3_BUCKET/

   deploy:
     <<: *defaults
     steps:
       - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/circleci/project

       - restore_cache:
           key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

       - run:
           name: Update Cloudformation Stack
           command: |
             export PATH="$HOME/.local/bin:$PATH"
             aws cloudformation update-stack \
               --stack-name $STACK_NAME-$CIRCLE_BRANCH \
               --region $AWS_DEFAULT_REGION \
               --template-url https://s3-$AWS_DEFAULT_REGION.amazonaws.com/$S3_BUCKET/cloudformation_stack.yaml \
               --parameters ParameterKey=TablePrefix,ParameterValue=$CIRCLE_BRANCH \
               --tags Key=project,Value=SecureLetter-$CIRCLE_BRANCH \
               --capabilities CAPABILITY_IAM

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          requires:
            - upload
          filters:
            branches:
              only:
                - master
                - develop
