version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     steps:
       - checkout

       - run:
           command: |
             export PATH="$HOME/.local/bin:$PATH"
             pip install --user pipenv
             pip install --user awscli
             python3 -m venv venv
             . venv/bin/activate
             pipenv install

       - run:
           command: |
             . venv/bin/activate
             make zip
             make deploy

       - store_artifacts:
           path: build/
           destination: bld
