version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     steps:
       - checkout

       - run:
           command: |
             python3 -m venv venv
             . venv/bin/activate
             pip install pipenv
             pip install awscli
             pipenv install

       - run:
           command: |
             make zip
             make deploy

       - store_artifacts:
           path: build/
           destination: bld
